language: java
sudo: false
script: mvn install -DcreateChecksum=true -Dtest=MailTestAllScenerio test
before_deploy: "echo 'ready?'"  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 65a63f6bcd0b985ef749dda74e568a27ee9ce872
  on:
    branch: master    
before_deploy: "echo 'Done'"

