language: java
sudo: false
script: mvn install -DcreateChecksum=true -Dtest=MailTestAllScenerio test
deploy:
    provider: script
    script: "mvn deploy"
    skip_cleanup: true
    on:
        branch: master
after_success: "echo 'Finish'"    