language: java
sudo: false
script: mvn install -DcreateChecksum=true -Dtest=MailTestAllScenerio test
before_deploy: "echo 'ready?'"  
deploy:
  provider: releases
  api_key: eeffc10cebda0f2920624bad5fa220e663a57924
  file: messagex-email-java-sdk-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true  
before_deploy: "echo 'Done'"